import { Router } from "express";
import BancoRoutes from "./routes/BancoRoutes";
import { CarreiraRoutes } from "./routes/CarreiraRoutes";
import { CategoriaRoutes } from "./routes/CategoriaRoutes";
import { CompetenciaRoutes } from "./routes/CompetenciaRoutes";
import { DadosProfissionaisRoutes } from "./routes/DadosProfissionaisRoutes";
import { DepartamentoRoutes } from "./routes/DepartamentoRoutes";
import { FichaAvaliacaoRoutes } from "./routes/FichaAvaliacaoRoutes";
import { FuncaoRoutes } from "./routes/FuncaoRoutes";
import { FuncionarioDepartamentoRoutes } from "./routes/FuncionarioDepartamentoRoutes";
import { FuncionarioRoutes } from "./routes/FuncionarioRoutes";
import { PerguntaFichaAvaliacaoRoutes } from "./routes/PergFichAvaliacaoRoutes";
import { PublicacaoRoutes } from "./routes/PublicacaoRoutes";
import { SubCarreiraRoutes } from "./routes/SubCarreirasRoutes";

const routes = Router();

routes.use("/funcao", FuncaoRoutes);
routes.use("/banco", BancoRoutes);
routes.use("/carreira", CarreiraRoutes);
routes.use("/categoria", CategoriaRoutes);
routes.use("/subcarreira", SubCarreiraRoutes);
routes.use("/funcionario", FuncionarioRoutes);
routes.use("/ficha-avaliacao", FichaAvaliacaoRoutes);
routes.use("/departamento", DepartamentoRoutes);
routes.use("/publicacao", PublicacaoRoutes);
routes.use("/competencia", CompetenciaRoutes);
routes.use("/perguntafichavaliacao", PerguntaFichaAvaliacaoRoutes);
routes.use("/funcionariodepartamento", FuncionarioDepartamentoRoutes);
routes.use("/dadosprofissionais", DadosProfissionaisRoutes);
export { routes };
